### PR TITLE
Changes for embedded graphics 0.7

### PR DESCRIPTION
**Pull request by flaminggoat**
Alpha version of embedded graphics is now available for 0.7. 0.7 has native support for drawing contiguous regions which provides a good performance increase.

### CODE REVIEW

**Comment by flaminggoat** [comment]
@sajattack Please could you consider this PR now the alpha of embedded graphics 0.7 is available.

**Comment by sajattack** [comment]
I'm slightly concerned that you're not using the buffer functions anymore, I'm pretty sure they are much faster. Have you compared speed between the two?

**Comment by flaminggoat** [comment]
Thanks for reviewing. I have changed the code to that use the buffered function, although when running a test filling the screen repeatedly I can see no appreciable difference in speed.

I'm not sure where the speed up is supposed to come from in the buffered function, as the same data is sent to display and I don't think embedded hal uses DMA. Also it would probably be good to use https://github.com/therealprof/display-interface so some of the generic functions can be removed from this crate, but that can be a separate PR.

**Comment by sajattack** [comment]
The version bump of our crate should be 0.8.0, we should bump our minor version if embedded graphics does.

**Comment by flaminggoat** [comment]
I have put it to 0.8.0-alpha.1 to avoid people selecting an incompatible version for the stable embedded-graphics.
I also changed a line in the lib to add the cfg feature for origin dimensions, which I think is supposed to be there?
```
#[cfg(feature = "graphics")]
impl<SPI, DC, RST> OriginDimensions for ST7735<SPI, DC, RST>
```

**Comment by sajattack** [comment]
Looks great, thanks!

**Pull request merged**
