### PR TITLE
Update for upcoming embedded-graphics release

### PR DESCRIPTION
**Pull request by jacobrosenthal**
For the master branch of embedded graphics (0.6.0 breaking changes I think)

### CODE REVIEW

**Comment by sajattack** [comment]
Maybe just set the version as "0.6" rather than "0.6.0-alpha2" so we don't have to change when it's officially released?

**Comment by jacobrosenthal** [comment]
EG is out
https://github.com/jamwaffles/embedded-graphics/blob/master/embedded-graphics/MIGRATING-0.5-0.6.md
I think this has the minimal changes

**Comment by sajattack** [comment]
Thanks!

**Comment by jacobrosenthal** [comment]
release? :)

**Comment by sajattack** [comment]
already done.

**Pull request merged**
